# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniforge/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/miniforge/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export ZSH="$ZDOTDIR/ohmyzsh"
export ZSH_DISABLE_COMPFIX=true
export UPDATE_ZSH_DAYS=7
export DISABLE_UPDATE_PROMPT=true
export COMPLETION_WAITING_DOTS=false
export plugins=(git fzf fzf-tab docker docker-compose docker-machine)


[ ! -d "$ZSH" ] && git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh "$ZSH"
[ ! -d "$ZSH/plugins/fzf-tab" ] && \
    git clone --depth=1 https://github.com/Aloxaf/fzf-tab "$ZSH/plugins/fzf-tab"

for src in $ZSH/oh-my-zsh.sh $ZDOTDIR/prompt $RCFG_DIR/{functions,variables}; do
    source $src
done

compdef _git g
compdef _docker dc
compdef _docker-compose dcc
compdef _docker-machine dcm

source $HOME/.nix-profile/etc/profile.d/nix.sh
eval "$(direnv hook zsh)"
source $(nix-build '<nixpkgs>' -A zsh-completions)/share/zsh/site-functions/*

